### ISSUE TITLE
Jitpack compatibility

### ISSUE THREAD

**Issue by AKuederle** [mad-lab-fau/SensorLib#5]
Jitpack can be used to make libraries published on Github easily integrateabel in other Android projects.
You just need to conform with the repo structure and jitpack does the rest.

https://jitpack.io/docs/ANDROID/

**Comment by nightscape** [comment]
Hi @AKuederle, I started working on this in https://github.com/gradlman/SensorLib/pull/8
You can give it a try and comment in the PR.
